output = open('output.txt', 'w', encoding='utf8')

new_cards = [
    "Alba-Lenatus the Abyss Dragon",
    "Albion the Branded Dragon",
    "Albion the Sanctifire Dragon",
    "Aleister the Invoker",
    "Alien Shocktrooper",
    "Ally of Justice Clausolas",
    "Amorphactor Pain, the Imagination Dracoverlord",
    "Amorphous Persona",
    "Amphibian Beast",
    "Amulet Dragon",
    "Archfiend Soldier",
    "Archfiend's Awakening",
    "Archfiend's Manifestation",
    "Battle Footballer",
    "Beast of Talwar",
    "Beckoned by the World Chalice",
    "Bitron",
    "Blazing Cartesia, the Virtuous",
    "Blazing Inpachi",
    "Blowback Dragon",
    "Blue-Eyes Chaos Dragon",
    "Blue-Eyes Twin Burst Dragon",
    "Blue-Eyes Tyrant Dragon",
    "Borreload Riot Dragon",
    "Brigrand the Glory Dragon",
    "Bunilla",
    "Buster Blader, the Dragon Destroyer Swordsman",
    "Cerulean Sacred Phoenix of Nephthys",
    "Chamberlain of the Six Samurai",
    "Chaos Form",
    "Charcoal Inpachi",
    "Clavkiys, the Magikey Skyblaster",
    "Conductor of Nephthys",
    "Contract with the Abyss",
    "Crowned by the World Chalice",
    "Curse of the Masked Beast",
    "Cyber Dragon",
    "Cyber Ogre",
    "Cyber Ogre 2",
    "Cyber Twin Dragon",
    "D.D. Trainer",
    "Dark Blade",
    "Dark Cavalry",
    "Dark Magician Girl the Dragon Knight",
    "Dark Magician the Dragon Knight",
    "Dark Magician the Knight of Dragon Magic",
    "Dark Paladin",
    "Darklord Marie",
    "Dawn of the Herald",
    "Divine Dragon Ragnarok",
    "Divine Grace - Northwemko",
    "Dogmatikamacabre",
    "Earthbound Spirit",
    "Elemental HERO Clayman",
    "Empress Mantis",
    "Evigishki Mind Augus",
    "Evigishki Soul Ogre",
    "Evigishki Tetrogre",
    "Evilswarm Heliotrope",
    "Fallen of Albaz",
    "Frostosaurus",
    "Gagagigo",
    "Gatling Dragon",
    "Gearfried the Red-Eyes Iron Knight",
    "Gem-Knight Garnet",
    "Gem-Knight Garnet",
    "Gem-Knight Ruby",
    "Gem-Knight Sapphire",
    "Giga Gagagigo",
    "Gil Garth",
    "Girochin Kuwagata",
    "Gishki Nekromirror",
    "Gishki Nekromirror",
    "Gishki Nekromirror",
    "Gladiator Beast Andal",
    "Good & Evil in the Burning Abyss",
    "Granguignol the Dusk Dragon",
    "Grapha, Dragon Lord of Dark World",
    "Grapha, Dragon Overlord of Dark World",
    "Great Angus",
    "Heavy Interlock",
    "Herald of Perfection",
    "Humanoid Slime",
    "Hunter Dragon",
    "Hymn of Light",
    "Inpachi",
    "Insect Knight",
    "Invoked Augoeides",
    "Invoked Purgatrio",
    "Island Turtle",
    "Jerry Beans Man",
    "Kabazauls",
    "King Dragun",
    "Legendary Dueling Field",
    "Libromancer Bonded",
    "Libromancer Bonded",
    "Libromancer Doombroker",
    "Libromancer Fireburst",
    "Light Bringer Lucifer",
    "Lubellion the Searing Dragon",
    "Luster Dragon",
    "Luster Dragon #2",
    "Mad Dog of Darkness",
    "Mad Lobster",
    "Magikey Maftea",
    "Magikey Maftea",
    "Magikey Mechmortar - Garesglasser",
    "Magikey Mechmusket - Batosbuster",
    "Malacoda, Netherlord of the Burning Abyss",
    "Master Kyonshee",
    "Master of Chaos",
    "Megalith Aratron",
    "Megalith Hagith",
    "Megalith Och",
    "Megalith Ophiel",
    "Megalith Phul",
    "Megalith Unformed",
    "Megalith Unformed",
    "Megalith Unformed",
    "Megalith Unformed",
    "Megalith Unformed",
    "Melffy Rabby",
    "Mirrorjade the Iceblade Dragon",
    "Nekroz Kaleidoscope",
    "Nekroz Kaleidoscope",
    "Nekroz Kaleidoscope",
    "Nekroz of Clausolas",
    "Nekroz of Unicore",
    "Nekroz of Valkyrus",
    "Neo Aqua Madoor",
    "Neo Bug",
    "Nin-Ken Dog",
    "Noble Knight Artorigus",
    "Odd-Eyes Advent",
    "Odd-Eyes Gravity Dragon",
    "Oppressed People",
    "Opticlops",
    "Primal Cry",
    "PSY-Frame Driver",
    "Rebirth of Nephthys",
    "Rebirth of Nephthys",
    "Red-Eyes Dark Dragoon",
    "Red-Eyes Slash Dragon",
    "Renge, Gatekeeper of Dark World",
    "Revendread Executor",
    "Revendread Origin",
    "Revendread Origin",
    "Revendread Origin",
    "Revendread Origin",
    "Rindbrumm the Striking Dragon",
    "Rise of the Salamangreat",
    "Ritual of Grace",
    "Sabersaurus",
    "Saffira, Queen of Dragons",
    "Salamangreat Emerald Eagle",
    "Sauravis, the Ancient and Ascended",
    "Sea Serpent Warrior of Darkness",
    "Shinato, King of a Higher Plane",
    "Shinato's Ark",
    "Shinobaron Peacock",
    "Shinobaroness Peacock",
    "Shinobird's Calling",
    "Shinobird's Calling",
    "Skull Dog Marron",
    "Sonic Duck",
    "Sonic Tracker",
    "Soul Tiger",
    "Space Mambo",
    "Sprind the Irondash Dragon",
    "Sprite's Blessing",
    "St. Joan",
    "Terrorking Salmon",
    "The Dark Magicians",
    "The Dragon Dwelling in the Cave",
    "The Forgiving Maiden",
    "The King of D.",
    "The Masked Beast",
    "Titaniklad the Ash Dragon",
    "Trance the Magic Swordsman",
    "Transonic Bird",
    "Vendread Battlelord",
    "Vendread Chimera",
    "Vendread Scavenger",
    "Vennu, Bright Bird of Divinity",
    "Venom Cobra",
    "Warrior Dai Grepher",
    "Wattaildragon",
    "White Relic of Dogmatika",
    "Wolf Axwielder",
    "X-Head Cannon",
    "X-Saber Anu Piranha",
    "XZ-Tank Cannon",
    "Z-Metal Tank",
    "Zure, Knight of Dark World"
]

count = 0
for card in data.cards.internalnumbers:
  if count < 194:
      if card.index != 'None':
        output.write("   '''" + card.index + "''',\n")
      else:
        output.write("   '''" + new_cards[count] + "''',\n")
        count = count + 1

output.close()